/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    bolts: THREE.Mesh;
  };
  materials: {
    Metal_Grey_Plain: THREE.MeshStandardMaterial;
  };
};

export function Bolts(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/assets/models/bolts.gltf') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.bolts.geometry}
                material={materials.Metal_Grey_Plain}
                scale={0.025}
            />
        </group>
    );
}

useGLTF.preload('/assets/models/bolts.gltf');