/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF, useTexture } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Box02: THREE.Mesh;
  };
  materials: {
    ['_9_-_Default']: THREE.MeshStandardMaterial;
  };
};

export function Corpus(props: JSX.IntrinsicElements['group']) {
    const { nodes } = useGLTF('/assets/models/corpus.gltf') as GLTFResult;

    const [ blueTexture ] = useTexture([
        '/assets/textures/blue.jpg',
    ]);

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                scale={0.025}
            >
                <primitive object={nodes.Box02.geometry} />
                <meshStandardMaterial map={blueTexture} roughness={0.25} metalness={0.4}/>
            </mesh>
        </group>
    );
}

useGLTF.preload('/assets/models/corpus.gltf');