/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    reduct_1: THREE.Mesh;
    reduct_2: THREE.Mesh;
    reduct_3: THREE.Mesh;
    reduct_4: THREE.Mesh;
    reduct_5: THREE.Mesh;
    reduct_6: THREE.Mesh;
  };
  materials: {
    Metal_Chrome: THREE.MeshStandardMaterial;
  };
};

export function Reduckt(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/assets/models/reduckt.gltf') as GLTFResult;

    materials.Metal_Chrome.roughness = 0.2;
    materials.Metal_Chrome.metalness = 1;

    return (
        <group {...props} dispose={null}>
            <group
                position={[0, 0, 0.05]}
                scale={0.025}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.reduct_1.geometry}
                    material={materials.Metal_Chrome}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.reduct_2.geometry}
                    material={materials.Metal_Chrome}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.reduct_3.geometry}
                    material={materials.Metal_Chrome}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.reduct_4.geometry}
                    material={materials.Metal_Chrome}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.reduct_5.geometry}
                    material={materials.Metal_Chrome}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.reduct_6.geometry}
                    material={materials.Metal_Chrome}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/assets/models/reduckt.gltf');