/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF, useTexture } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { OperationsNames } from '../../types';
import { useRef } from 'react';
import { Group } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Box02: THREE.Mesh;
  };
  materials: {
    ['_9_-_Default']: THREE.MeshStandardMaterial;
  };
};

interface regProps {
    operationId: string;
    onActive: (active: boolean) => void;
    props?: JSX.IntrinsicElements['group']
}

export const Corpus: React.FC<regProps> = ({operationId, onActive, props}) => {
    const modelRef = useRef<Group>(null!);

    const { nodes } = useGLTF('/assets/models/corpus.gltf') as GLTFResult;

    const [ blueTexture ] = useTexture([
        '/assets/textures/blue.jpg',
    ]);

    useFrame(() => {
        if(operationId === OperationsNames.OPR_8 && modelRef.current){
            if(modelRef.current.position.y <= 5){
                modelRef.current.position.y = modelRef.current.position.y + 0.05;
            } else {
                operationId = '';
            }
        }
        if(operationId === OperationsNames.OPR_9 && modelRef.current){
            if(modelRef.current.position.y >= 0){
                modelRef.current.position.y = modelRef.current.position.y - 0.1;
            }
        }
    });

    return (
        <group {...props} ref={modelRef} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                scale={0.025}
            >
                <primitive object={nodes.Box02.geometry} />
                <meshStandardMaterial map={blueTexture} roughness={0.25} metalness={0.4}/>
            </mesh>
        </group>
    );
};

useGLTF.preload('/assets/models/corpus.gltf');