/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF, useTexture } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder18_1: THREE.Mesh;
    Cylinder18_2: THREE.Mesh;
    Cylinder18_3: THREE.Mesh;
  };
  materials: {
    ['_9_-_Default']: THREE.MeshStandardMaterial;
    Metal_Latun_Plain: THREE.MeshStandardMaterial;
    Metal_Grey_Plain: THREE.MeshStandardMaterial;
  };
};

export function FrontCup(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/assets/models/frontCup.gltf') as GLTFResult;

    const [ blueTexture ] = useTexture([
        '/assets/textures/blue.jpg',
    ]);

    materials.Metal_Latun_Plain.roughness = 0.2;
    materials.Metal_Latun_Plain.metalness = 0.8;

    materials.Metal_Grey_Plain.roughness = 0.2;
    materials.Metal_Grey_Plain.metalness = 0.8;

    return (
        <group {...props} dispose={null}>
            <group rotation={[1.57, 1.18, -3.14]} scale={0.025}>
                <mesh
                    castShadow
                    receiveShadow
                >
                    <primitive object={nodes.Cylinder18_1.geometry} />
                    <meshStandardMaterial map={blueTexture} roughness={0.25} metalness={0.4}/>
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder18_2.geometry}
                    material={materials.Metal_Latun_Plain}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder18_3.geometry}
                    material={materials.Metal_Grey_Plain}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/assets/models/frontCup.gltf');