/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
import { Group } from 'three';
import { OperationsNames } from '../../types';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder32: THREE.Mesh;
  };
  materials: {
    Metal_Grey_Plain: THREE.MeshStandardMaterial;
  };
};

interface regProps {
  operationId: string;
  onActive: (active: boolean) => void;
  props?: JSX.IntrinsicElements['group']
}

export const Screw: React.FC<regProps> = ({operationId, onActive, props}) => {
    const modelRef = useRef<Group>(null!);

    const { nodes, materials } = useGLTF('/assets/models/screw.gltf') as GLTFResult;

    materials.Metal_Grey_Plain.roughness = 0.1;
    materials.Metal_Grey_Plain.metalness = 0.9;

    useFrame(() => {
        if(operationId === OperationsNames.OPR_3 && modelRef.current){
            if(modelRef.current.position.z <= 9){
                modelRef.current.position.z = modelRef.current.position.z + 0.1;
            } else {
                operationId = '';
                onActive(false);
            }
        }
    });

    return (
        <group {...props} ref={modelRef} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder32.geometry}
                material={materials.Metal_Grey_Plain}
                rotation={[-Math.PI / 2, Math.PI / 8, -Math.PI]}
                scale={0.025}
            />
        </group>
    );
};

useGLTF.preload('/assets/models/screw.gltf');